#!/bin/bash
sudo chown root /usr/lib64/enlightenment/modules/cpufreq/linux-gnu-x86_64-ver-serious-0.19/freqset
sudo chmod u+s,a+x /usr/lib64/enlightenment/modules/cpufreq/linux-gnu-x86_64-ver-serious-0.19/freqset
